trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/**

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Terraform
  displayName: 'Provision Infrastructure'
  jobs:
  - job: Terraform_Apply
    displayName: 'Terraform Apply'
    steps:

    - task: DownloadSecureFile@1
      name: ssh_key
      inputs:
        secureFile: 'epicbook-key'

    - script: |
        mkdir -p terraform/modules/compute
        cp $(ssh_key.secureFilePath) terraform/modules/compute/epicbook-key
      displayName: 'Place SSH Key'

    - task: AzureCLI@2
      displayName: 'Terraform Init, Plan, Apply'
      inputs:
        azureSubscription: 'it-azure-connection'
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/terraform
        inlineScript: |
          terraform init -input=false
          terraform plan -input=false -var-file="envs/dev.tfvars"
          terraform apply -input=false -auto-approve -var-file="envs/dev.tfvars"